namespace NomadicMethod.Models;

public enum CanonicalMuscleGroup
{
    MedialAndDeepKneeExtensors = 1,
    PosteriorThighAndKneeFlexors = 2,
    MajorHipAdductors = 3,
    LateralKneeExtensors = 4,
    GlutealExtensors = 5,
    SpinalExtensors = 6,
    CalfDeepPosteriorLegAndPlantarFoot = 7,
    Soleus = 8,
    ScapularGirdle = 9,
    ShoulderAdductorsAndExtensors = 10,
    AbdominalWall = 11,
    HipAbductors = 12,
    Chest = 13,
    ElbowExtensors = 14,
    HipFlexors = 15,
    AnteriorLateralLowerLegAndDorsalFoot = 16,
    DeepHipRotators = 17,
    ShoulderAbductors = 18,
    ForearmFlexorsAndPronators = 19,
    DeepAndIntersegmentalBack = 20,
    ElbowFlexors = 21,
    BreathingMuscles = 22,
    ForearmExtensorsAndSupinators = 23,
    RotatorCuff = 24,
    AccessoryHipAdductors = 25,
    PosteriorNeckAndSuboccipitalMuscles = 26,
    CranialMuscles = 27,
    AnteriorLateralNeckAndHyoidMuscles = 28,
    IntrinsicHand = 29,
    PelvicFloorAndPerineum = 30,
}
